service: citematic-backend

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  stage: dev
  environment:
    YOUTUBE_API_KEY: ${env:YOUTUBE_API_KEY, ssm:/citematic/youtubeApiKey}
    DEBUG: ${env:DEBUG, 'false'}

functions:
  generateCitation:
    handler: src/handler.generateCitation
    events:
      - http:
          path: generate-citation
          method: post
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001